language: python

matrix:
  fast_finish: true
  include:
    - python: 3.7
      # from https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
      dist: xenial
      env: TOXENV=py37
      sudo: true
before_install:
  - sudo rm -f /etc/boto.cfg
  - export BOTO_CONFIG=/dev/null
  - export AWS_SECRET_ACCESS_KEY=foobar_secret
  - export AWS_ACCESS_KEY_ID=foobar_key
install:
  - travis_retry pip install -r requirements/test.txt
  - pip install -e git+https://github.com/spulec/moto@master#egg=moto
  - python setup.py develop
script:
  - py.test --cov-config .coveragerc --cov=taskhuddler --cov-report term-missing
  - flake8
